name: Bug 报告（中文）
description: 这里有些不对劲，可能是一个 Bug
labels: [ ]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug 描述
      description: |
        清晰简洁地描述这个 Bug 是什么。
        是游戏崩溃，意外行为，还是出了什么问题？
        如果适用，请添加截图来帮助解释这个 Bug。
      placeholder: 告诉我们你看到了什么！
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: 重现步骤
      description: 重现该 Bug 的步骤
      placeholder: |
        1. 创建一个新的世界
        2. 等到午夜
        3. 拥抱一个苦力怕
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期行为
      description: 你期望发生什么？
      placeholder: 苦力怕爆炸
  - type: textarea
    id: actual-behavior
    attributes:
      label: 实际行为
      description: 实际发生了什么？
      placeholder: 苦力怕旋转着飞上天
  - type: textarea
    id: logs
    attributes:
      label: 相关日志
      description: |
        如果是崩溃，请在这里发送对应的 Minecraft 日志（位于 `logs` 文件夹）或崩溃报告（位于 `crash-reports` 文件夹）。
        请将日志文件作为 Github 附件上传，或将日志上传至 [pastebin](https://pastebin.com/) / [mclo.gs](https://mclo.gs/) 并粘贴 URL 到这里。
        如果没有，可以留空。
      placeholder: https://pastebin.com/******
  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft 版本
      description: 该 Bug 出现在哪个 Minecraft 版本中。
      placeholder: 1.20.4
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod 版本
      description: 该 Bug 出现在哪个 Mod 版本中。
      placeholder: 2.2.0
    validations:
      required: true
  - type: textarea
    id: other-information
    attributes:
      label: 其他信息
      description: 该 Bug 报告的其他有用信息，例如其他相关的 Mod 版本。如果没有，可以留空。
      placeholder: 此 Bug 仅在玩家处于生存模式时发生
  - type: checkboxes
    id: check-list
    attributes:
      label: 检查列表
      options:
        - label: 我已经确认问题在最新版本的 Mod 中仍然存在。
          required: true
        - label: 我已经搜索过现有问题，确认这不是重复的。
          required: true