name: build
on: [ pull_request, push ]

jobs:
  commit-checker:
    runs-on: ubuntu-latest
    outputs:
      skip_build: ${{ steps.check.outputs.skip_build }}
    steps:
      - uses: actions/checkout@v4

      - name: Check commit message
        id: check
        run: |
          commit_message=$(git log -1 --pretty=%B)
          echo "Commit message: $commit_message"
          if [[ "$commit_message" == *"[skip ci]"* ]]; then
            echo "Skipping CI..."
            echo "skip_build=true" >> $GITHUB_OUTPUT
          else
            echo "Confirming CI..."
            echo "skip_build=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: commit-checker
    if: needs.commit-checker.outputs.skip_build == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/actions/build

  summary:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts
          path: gathered-artifacts

      - name: Make build summary
        run: python3 .github/workflows/scripts/summary.py  # ubuntu-22.04 uses Python 3.10.6
        env:
          TARGET_SUBPROJECT: '' # leaving this empty means all subprojects
